from __future__ import annotations

import random
from typing import Optional

# Banque de questions de culture générale (FR). Chaque entrée : question, réponse, explication, difficulté.
# difficulté ∈ {"facile", "moyen", "difficile"}.
CULTURE_QUESTIONS: list[dict[str, str]] = [
    # --- Facile ---
    {"question": "Quelle est la capitale de la France ?", "answer": "Paris", "explanation": "Paris est la capitale de la France depuis le Moyen Âge.", "difficulty": "facile"},
    {"question": "Combien y a-t-il de jours dans une année non bissextile ?", "answer": "365", "explanation": "Une année bissextile en compte 366 (29 février).", "difficulty": "facile"},
    {"question": "De quelle couleur est le ciel par temps clair ?", "answer": "Bleu", "explanation": "La diffusion de Rayleigh disperse surtout la lumière bleue.", "difficulty": "facile"},
    {"question": "Quel animal est le meilleur ami de l'homme ?", "answer": "Le chien", "explanation": "Le chien est domestiqué depuis plus de 15 000 ans.", "difficulty": "facile"},
    {"question": "Combien de pattes a une araignée ?", "answer": "8", "explanation": "Les araignées sont des arachnides à 8 pattes, contrairement aux insectes (6).", "difficulty": "facile"},
    {"question": "Quel est le premier nombre premier ?", "answer": "2", "explanation": "2 est le seul nombre premier pair.", "difficulty": "facile"},
    {"question": "Quelle planète habitons-nous ?", "answer": "La Terre", "explanation": "La Terre est la 3e planète du système solaire.", "difficulty": "facile"},
    {"question": "Quel sport pratique-t-on à Roland-Garros ?", "answer": "Le tennis", "explanation": "Roland-Garros est le tournoi du Grand Chelem sur terre battue.", "difficulty": "facile"},
    {"question": "Combien de joueurs composent une équipe de football sur le terrain ?", "answer": "11", "explanation": "Onze joueurs par équipe, dont un gardien.", "difficulty": "facile"},
    {"question": "Quelle est la couleur obtenue en mélangeant le bleu et le jaune ?", "answer": "Le vert", "explanation": "Bleu + jaune donne du vert en synthèse soustractive.", "difficulty": "facile"},
    {"question": "Quel est l'astre qui éclaire la Terre le jour ?", "answer": "Le Soleil", "explanation": "Le Soleil est l'étoile au centre de notre système.", "difficulty": "facile"},
    {"question": "Dans quel pays se trouve la tour Eiffel ?", "answer": "La France", "explanation": "Construite à Paris pour l'Exposition universelle de 1889.", "difficulty": "facile"},
    # --- Moyen ---
    {"question": "Qui a peint la Joconde ?", "answer": "Léonard de Vinci", "explanation": "Œuvre du début du XVIe siècle, exposée au Louvre.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand océan du monde ?", "answer": "L'océan Pacifique", "explanation": "Il couvre environ un tiers de la surface du globe.", "difficulty": "moyen"},
    {"question": "En quelle année a eu lieu la Révolution française ?", "answer": "1789", "explanation": "La prise de la Bastille a lieu le 14 juillet 1789.", "difficulty": "moyen"},
    {"question": "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", "answer": "Le dioxyde de carbone (CO2)", "explanation": "Elles rejettent de l'oxygène en retour.", "difficulty": "moyen"},
    {"question": "Quelle est la monnaie du Japon ?", "answer": "Le yen", "explanation": "Le yen est la 3e monnaie la plus échangée au monde.", "difficulty": "moyen"},
    {"question": "Combien de côtés possède un hexagone ?", "answer": "6", "explanation": "« Hexa » signifie six en grec.", "difficulty": "moyen"},
    {"question": "Qui a écrit « Les Misérables » ?", "answer": "Victor Hugo", "explanation": "Roman publié en 1862.", "difficulty": "moyen"},
    {"question": "Quel est le plus haut sommet du monde ?", "answer": "L'Everest", "explanation": "Culmine à 8 849 m dans l'Himalaya.", "difficulty": "moyen"},
    {"question": "Quel organe pompe le sang dans le corps ?", "answer": "Le cœur", "explanation": "Il bat environ 100 000 fois par jour.", "difficulty": "moyen"},
    {"question": "Quel pays a remporté la Coupe du monde de football 2018 ?", "answer": "La France", "explanation": "Victoire 4-2 contre la Croatie en finale.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de l'Australie ?", "answer": "Canberra", "explanation": "Et non Sydney, souvent confondue.", "difficulty": "moyen"},
    {"question": "Combien de continents y a-t-il sur Terre ?", "answer": "7", "explanation": "Afrique, Amérique du Nord, Amérique du Sud, Antarctique, Asie, Europe, Océanie.", "difficulty": "moyen"},
    # --- Difficile ---
    {"question": "Quel est l'élément chimique de symbole « Au » ?", "answer": "L'or", "explanation": "De son nom latin « aurum ».", "difficulty": "difficile"},
    {"question": "En quelle année est tombé le mur de Berlin ?", "answer": "1989", "explanation": "Le 9 novembre 1989, symbole de la fin de la guerre froide.", "difficulty": "difficile"},
    {"question": "Qui a formulé la théorie de la relativité générale ?", "answer": "Albert Einstein", "explanation": "Publiée en 1915.", "difficulty": "difficile"},
    {"question": "Quelle est la plus longue rivière du monde ?", "answer": "L'Amazone (ou le Nil)", "explanation": "Le débat Amazone/Nil dépend de la méthode de mesure.", "difficulty": "difficile"},
    {"question": "Combien d'os compte le corps humain adulte ?", "answer": "206", "explanation": "Un nouveau-né en a environ 270, certains fusionnent.", "difficulty": "difficile"},
    {"question": "Quel philosophe grec fut le maître d'Alexandre le Grand ?", "answer": "Aristote", "explanation": "Aristote, élève de Platon, précepteur d'Alexandre.", "difficulty": "difficile"},
    {"question": "Quelle est la vitesse de la lumière dans le vide (ordre de grandeur) ?", "answer": "300 000 km/s", "explanation": "Précisément 299 792 458 m/s.", "difficulty": "difficile"},
    {"question": "Quel pays compte le plus d'habitants au monde ?", "answer": "L'Inde", "explanation": "L'Inde a dépassé la Chine en 2023.", "difficulty": "difficile"},
    {"question": "Qui a peint « La Nuit étoilée » ?", "answer": "Vincent van Gogh", "explanation": "Peinte en 1889 à Saint-Rémy-de-Provence.", "difficulty": "difficile"},
    {"question": "Quel est le plus petit pays du monde ?", "answer": "Le Vatican", "explanation": "Environ 44 hectares.", "difficulty": "difficile"},
    {"question": "En quelle année l'homme a-t-il marché sur la Lune pour la première fois ?", "answer": "1969", "explanation": "Mission Apollo 11, le 21 juillet 1969.", "difficulty": "difficile"},
    {"question": "Quelle est la formule chimique de l'eau ?", "answer": "H2O", "explanation": "Deux atomes d'hydrogène, un d'oxygène.", "difficulty": "difficile"},
    # --- Facile (suite) ---
    {"question": "Quelle est la couleur d'une banane mûre ?", "answer": "Jaune", "explanation": "Verte avant maturité, elle jaunit en mûrissant.", "difficulty": "facile"},
    {"question": "Combien de roues a une voiture ordinaire ?", "answer": "4", "explanation": "Quatre roues, plus parfois une de secours.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « chaud » ?", "answer": "Froid", "explanation": "Antonyme de température.", "difficulty": "facile"},
    {"question": "Dans quelle ville se trouve la statue de la Liberté ?", "answer": "New York", "explanation": "Offerte par la France en 1886.", "difficulty": "facile"},
    {"question": "Quel fruit est associé à Isaac Newton et la gravité ?", "answer": "La pomme", "explanation": "La légende de la pomme qui tombe.", "difficulty": "facile"},
    {"question": "Combien de minutes y a-t-il dans une heure ?", "answer": "60", "explanation": "60 minutes, 3600 secondes.", "difficulty": "facile"},
    {"question": "Quel animal rugit dans la savane et est appelé « roi » ?", "answer": "Le lion", "explanation": "Surnommé le roi des animaux.", "difficulty": "facile"},
    {"question": "Quelle est la première lettre de l'alphabet français ?", "answer": "A", "explanation": "L'alphabet latin commence par A.", "difficulty": "facile"},
    {"question": "Quel liquide boit-on principalement pour s'hydrater ?", "answer": "L'eau", "explanation": "Essentielle à la vie.", "difficulty": "facile"},
    {"question": "Quel jour vient après le lundi ?", "answer": "Mardi", "explanation": "Ordre des jours de la semaine.", "difficulty": "facile"},
    {"question": "Combien de doigts a-t-on sur une main ?", "answer": "5", "explanation": "Cinq doigts par main.", "difficulty": "facile"},
    {"question": "Quel est l'emblème végétal du Canada (sur son drapeau) ?", "answer": "La feuille d'érable", "explanation": "Symbole national canadien.", "difficulty": "facile"},
    {"question": "Quelle saison vient après l'hiver ?", "answer": "Le printemps", "explanation": "Hiver → printemps → été → automne.", "difficulty": "facile"},
    {"question": "Quel est le petit du chat ?", "answer": "Le chaton", "explanation": "Le chaton est le bébé chat.", "difficulty": "facile"},
    {"question": "Combien font 5 + 7 ?", "answer": "12", "explanation": "Addition simple.", "difficulty": "facile"},
    # --- Moyen (suite) ---
    {"question": "Quel fleuve traverse Paris ?", "answer": "La Seine", "explanation": "La Seine traverse la capitale d'est en ouest.", "difficulty": "moyen"},
    {"question": "Quel est le symbole chimique de l'oxygène ?", "answer": "O", "explanation": "O, numéro atomique 8.", "difficulty": "moyen"},
    {"question": "Qui était le premier président de la Ve République française ?", "answer": "Charles de Gaulle", "explanation": "Élu en 1958.", "difficulty": "moyen"},
    {"question": "Combien de cordes possède une guitare classique ?", "answer": "6", "explanation": "Six cordes standard.", "difficulty": "moyen"},
    {"question": "Quelle est la planète la plus proche du Soleil ?", "answer": "Mercure", "explanation": "Première planète du système solaire.", "difficulty": "moyen"},
    {"question": "Dans quel pays se trouve le Colisée ?", "answer": "L'Italie", "explanation": "À Rome, amphithéâtre antique.", "difficulty": "moyen"},
    {"question": "Quel peintre s'est coupé l'oreille ?", "answer": "Vincent van Gogh", "explanation": "Épisode célèbre de 1888 à Arles.", "difficulty": "moyen"},
    {"question": "Quelle est la langue la plus parlée au monde (locuteurs natifs) ?", "answer": "Le chinois mandarin", "explanation": "Plus d'un milliard de locuteurs natifs.", "difficulty": "moyen"},
    {"question": "Combien de joueurs dans une équipe de basket sur le terrain ?", "answer": "5", "explanation": "Cinq joueurs par équipe.", "difficulty": "moyen"},
    {"question": "Quel est l'organe principal de la respiration ?", "answer": "Les poumons", "explanation": "Échangent l'oxygène et le CO2.", "difficulty": "moyen"},
    {"question": "Quelle mer borde la Côte d'Azur ?", "answer": "La mer Méditerranée", "explanation": "Au sud-est de la France.", "difficulty": "moyen"},
    {"question": "Qui a composé « La Symphonie n°9 » et était sourd ?", "answer": "Ludwig van Beethoven", "explanation": "Composée alors qu'il était devenu sourd.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand désert chaud du monde ?", "answer": "Le Sahara", "explanation": "En Afrique du Nord.", "difficulty": "moyen"},
    {"question": "En quelle année a commencé la Première Guerre mondiale ?", "answer": "1914", "explanation": "De 1914 à 1918.", "difficulty": "moyen"},
    {"question": "Quel métal précieux a pour symbole « Ag » ?", "answer": "L'argent", "explanation": "Du latin « argentum ».", "difficulty": "moyen"},
    # --- Difficile (suite) ---
    {"question": "Qui a écrit « À la recherche du temps perdu » ?", "answer": "Marcel Proust", "explanation": "Œuvre en sept tomes (1913-1927).", "difficulty": "difficile"},
    {"question": "Quelle est la capitale du Canada ?", "answer": "Ottawa", "explanation": "Et non Toronto ou Montréal.", "difficulty": "difficile"},
    {"question": "Combien de chromosomes possède l'être humain ?", "answer": "46", "explanation": "23 paires de chromosomes.", "difficulty": "difficile"},
    {"question": "Quel scientifique a découvert la pénicilline ?", "answer": "Alexander Fleming", "explanation": "En 1928, premier antibiotique.", "difficulty": "difficile"},
    {"question": "Quelle est la monnaie utilisée en Suisse ?", "answer": "Le franc suisse", "explanation": "Code CHF.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand mammifère terrestre ?", "answer": "L'éléphant d'Afrique", "explanation": "Peut peser plus de 6 tonnes.", "difficulty": "difficile"},
    {"question": "Qui a peint le plafond de la chapelle Sixtine ?", "answer": "Michel-Ange", "explanation": "Entre 1508 et 1512.", "difficulty": "difficile"},
    {"question": "Quel pays a inventé le papier ?", "answer": "La Chine", "explanation": "Invention attribuée à Cai Lun (105 apr. J.-C.).", "difficulty": "difficile"},
    {"question": "Quelle planète est surnommée la planète rouge ?", "answer": "Mars", "explanation": "Sa surface riche en oxyde de fer.", "difficulty": "difficile"},
    {"question": "Quel traité a créé la Communauté économique européenne en 1957 ?", "answer": "Le traité de Rome", "explanation": "Signé par six pays fondateurs.", "difficulty": "difficile"},
    {"question": "Combien de symphonies Beethoven a-t-il composées ?", "answer": "9", "explanation": "La 9e contient l'« Hymne à la joie ».", "difficulty": "difficile"},
    {"question": "Quel est l'élément le plus abondant dans l'univers ?", "answer": "L'hydrogène", "explanation": "Environ 75 % de la matière baryonique.", "difficulty": "difficile"},
    {"question": "Qui a théorisé l'inconscient et fondé la psychanalyse ?", "answer": "Sigmund Freud", "explanation": "Fin du XIXe – début XXe siècle.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale du Brésil ?", "answer": "Brasília", "explanation": "Et non Rio de Janeiro ou São Paulo.", "difficulty": "difficile"},
    {"question": "En quelle année a été signée la Déclaration des droits de l'homme et du citoyen ?", "answer": "1789", "explanation": "Le 26 août 1789, pendant la Révolution.", "difficulty": "difficile"},
    # --- Facile (lot 3) ---
    {"question": "De quelle couleur est l'herbe ?", "answer": "Verte", "explanation": "Grâce à la chlorophylle.", "difficulty": "facile"},
    {"question": "Quel oiseau est connu pour répéter ce qu'on lui dit ?", "answer": "Le perroquet", "explanation": "Il imite les sons et la parole.", "difficulty": "facile"},
    {"question": "Combien de mois compte une année ?", "answer": "12", "explanation": "De janvier à décembre.", "difficulty": "facile"},
    {"question": "Quel est l'astre que l'on voit la nuit et qui change de forme ?", "answer": "La Lune", "explanation": "Ses phases vont du croissant à la pleine lune.", "difficulty": "facile"},
    {"question": "Quel sport se joue avec un ballon rond au pied ?", "answer": "Le football", "explanation": "Sport le plus populaire au monde.", "difficulty": "facile"},
    {"question": "Quelle est la capitale de l'Italie ?", "answer": "Rome", "explanation": "La « Ville éternelle ».", "difficulty": "facile"},
    {"question": "Quel animal fait « meuh » ?", "answer": "La vache", "explanation": "Le meuglement de la vache.", "difficulty": "facile"},
    {"question": "Combien y a-t-il de couleurs dans un arc-en-ciel ?", "answer": "7", "explanation": "Rouge, orange, jaune, vert, bleu, indigo, violet.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « grand » ?", "answer": "Petit", "explanation": "Antonyme de taille.", "difficulty": "facile"},
    {"question": "Quelle boisson chaude est faite à partir de grains torréfiés ?", "answer": "Le café", "explanation": "Issu des grains de caféier.", "difficulty": "facile"},
    {"question": "Combien de pattes a un chien ?", "answer": "4", "explanation": "Quatre pattes, comme la plupart des mammifères.", "difficulty": "facile"},
    {"question": "Quel objet sert à lire l'heure au poignet ?", "answer": "La montre", "explanation": "Instrument de mesure du temps porté au poignet.", "difficulty": "facile"},
    {"question": "Quelle est la capitale de l'Espagne ?", "answer": "Madrid", "explanation": "Au centre du pays.", "difficulty": "facile"},
    {"question": "Quel fruit jaune et acide presse-t-on pour la citronnade ?", "answer": "Le citron", "explanation": "Riche en vitamine C.", "difficulty": "facile"},
    {"question": "Combien font 10 moins 4 ?", "answer": "6", "explanation": "Soustraction simple.", "difficulty": "facile"},
    # --- Moyen (lot 3) ---
    {"question": "Quel pays a pour capitale Tokyo ?", "answer": "Le Japon", "explanation": "Tokyo est la plus grande aire urbaine du monde.", "difficulty": "moyen"},
    {"question": "Qui a écrit « Le Petit Prince » ?", "answer": "Antoine de Saint-Exupéry", "explanation": "Publié en 1943.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand pays du monde par superficie ?", "answer": "La Russie", "explanation": "Plus de 17 millions de km².", "difficulty": "moyen"},
    {"question": "Combien de touches a un piano standard ?", "answer": "88", "explanation": "52 blanches et 36 noires.", "difficulty": "moyen"},
    {"question": "Quel gaz respirons-nous principalement (le plus abondant dans l'air) ?", "answer": "L'azote", "explanation": "Environ 78 % de l'atmosphère.", "difficulty": "moyen"},
    {"question": "Dans quel pays a été inventée la pizza ?", "answer": "L'Italie", "explanation": "Originaire de Naples.", "difficulty": "moyen"},
    {"question": "Quel est le plus petit os du corps humain ?", "answer": "L'étrier", "explanation": "Situé dans l'oreille moyenne.", "difficulty": "moyen"},
    {"question": "Quelle chaîne de montagnes sépare la France et l'Espagne ?", "answer": "Les Pyrénées", "explanation": "Frontière naturelle au sud-ouest.", "difficulty": "moyen"},
    {"question": "En quelle année a sombré le Titanic ?", "answer": "1912", "explanation": "Dans la nuit du 14 au 15 avril 1912.", "difficulty": "moyen"},
    {"question": "Quel est le sport national du Japon ?", "answer": "Le sumo", "explanation": "Lutte traditionnelle japonaise.", "difficulty": "moyen"},
    {"question": "Qui a peint « Les Tournesols » ?", "answer": "Vincent van Gogh", "explanation": "Série célèbre de natures mortes.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de l'Allemagne ?", "answer": "Berlin", "explanation": "Depuis la réunification de 1990.", "difficulty": "moyen"},
    {"question": "Combien de côtés a un octogone ?", "answer": "8", "explanation": "« Octo » signifie huit.", "difficulty": "moyen"},
    {"question": "Quel océan sépare l'Europe de l'Amérique ?", "answer": "L'océan Atlantique", "explanation": "Deuxième plus grand océan.", "difficulty": "moyen"},
    {"question": "Quel est le nom du processus par lequel l'eau devient vapeur ?", "answer": "L'évaporation", "explanation": "Passage de l'état liquide à gazeux.", "difficulty": "moyen"},
    # --- Difficile (lot 3) ---
    {"question": "Quelle est l'unité de mesure de la résistance électrique ?", "answer": "L'ohm", "explanation": "Symbole Ω, du physicien Georg Ohm.", "difficulty": "difficile"},
    {"question": "Qui a écrit « Crime et Châtiment » ?", "answer": "Fiodor Dostoïevski", "explanation": "Roman russe de 1866.", "difficulty": "difficile"},
    {"question": "Quel empereur romain a fait construire un mur en Grande-Bretagne ?", "answer": "Hadrien", "explanation": "Le mur d'Hadrien, vers 122 apr. J.-C.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Égypte ?", "answer": "Le Caire", "explanation": "Plus grande ville d'Afrique du Nord.", "difficulty": "difficile"},
    {"question": "Quel mathématicien grec est connu pour son théorème sur le triangle rectangle ?", "answer": "Pythagore", "explanation": "a² + b² = c².", "difficulty": "difficile"},
    {"question": "Quelle planète possède les anneaux les plus visibles ?", "answer": "Saturne", "explanation": "Anneaux de glace et de roches.", "difficulty": "difficile"},
    {"question": "En quelle année a eu lieu la chute de l'Empire romain d'Occident ?", "answer": "476", "explanation": "Déposition de Romulus Augustule.", "difficulty": "difficile"},
    {"question": "Quel est le symbole chimique du sodium ?", "answer": "Na", "explanation": "Du latin « natrium ».", "difficulty": "difficile"},
    {"question": "Qui a réalisé le film « Pulp Fiction » ?", "answer": "Quentin Tarantino", "explanation": "Palme d'or à Cannes en 1994.", "difficulty": "difficile"},
    {"question": "Quel est le plus long fleuve d'Europe ?", "answer": "La Volga", "explanation": "Environ 3 530 km, en Russie.", "difficulty": "difficile"},
    {"question": "Combien de pays composent l'Union européenne (depuis le Brexit) ?", "answer": "27", "explanation": "Après le départ du Royaume-Uni en 2020.", "difficulty": "difficile"},
    {"question": "Quel philosophe a écrit « Le Discours de la méthode » ?", "answer": "René Descartes", "explanation": "1637, « Je pense, donc je suis ».", "difficulty": "difficile"},
    {"question": "Quelle est la vitesse du son dans l'air (ordre de grandeur) ?", "answer": "340 m/s", "explanation": "Environ 1 224 km/h à 20 °C.", "difficulty": "difficile"},
    {"question": "Quel pays a offert le café au monde via l'Éthiopie puis le Yémen ?", "answer": "L'Éthiopie", "explanation": "Berceau historique du caféier.", "difficulty": "difficile"},
    {"question": "Qui a peint « Guernica » ?", "answer": "Pablo Picasso", "explanation": "1937, en réaction au bombardement de Guernica.", "difficulty": "difficile"},
    # --- Facile (lot 4) ---
    {"question": "Quel animal vit dans une ruche et fabrique du miel ?", "answer": "L'abeille", "explanation": "Les abeilles produisent le miel.", "difficulty": "facile"},
    {"question": "Quelle est la couleur du sang ?", "answer": "Rouge", "explanation": "Dû à l'hémoglobine.", "difficulty": "facile"},
    {"question": "Combien de saisons y a-t-il dans une année ?", "answer": "4", "explanation": "Printemps, été, automne, hiver.", "difficulty": "facile"},
    {"question": "Quel est l'animal le plus grand du monde ?", "answer": "La baleine bleue", "explanation": "Peut dépasser 30 mètres.", "difficulty": "facile"},
    {"question": "Sur quel continent se trouve l'Égypte ?", "answer": "L'Afrique", "explanation": "Nord-est de l'Afrique.", "difficulty": "facile"},
    {"question": "Quel ustensile sert à manger la soupe ?", "answer": "La cuillère", "explanation": "Adaptée aux liquides.", "difficulty": "facile"},
    {"question": "Quelle planète habitons-nous, aussi appelée la planète bleue ?", "answer": "La Terre", "explanation": "Surnommée ainsi à cause des océans.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « jour » ?", "answer": "Nuit", "explanation": "Alternance jour/nuit.", "difficulty": "facile"},
    {"question": "Quel animal a une trompe ?", "answer": "L'éléphant", "explanation": "Sa trompe sert à boire et saisir.", "difficulty": "facile"},
    {"question": "Combien de jours y a-t-il dans une semaine ?", "answer": "7", "explanation": "Du lundi au dimanche.", "difficulty": "facile"},
    {"question": "Quelle est la capitale de l'Angleterre ?", "answer": "Londres", "explanation": "Sur la Tamise.", "difficulty": "facile"},
    {"question": "Quel légume orange aime le lapin ?", "answer": "La carotte", "explanation": "Riche en bêta-carotène.", "difficulty": "facile"},
    {"question": "Quel moyen de transport vole dans le ciel ?", "answer": "L'avion", "explanation": "Transport aérien.", "difficulty": "facile"},
    {"question": "Combien font 3 fois 3 ?", "answer": "9", "explanation": "Table de multiplication.", "difficulty": "facile"},
    {"question": "Quel est le métal d'une médaille de première place ?", "answer": "L'or", "explanation": "Or = 1er, argent = 2e, bronze = 3e.", "difficulty": "facile"},
    {"question": "Quel animal marin a huit bras ?", "answer": "La pieuvre", "explanation": "Aussi appelée poulpe.", "difficulty": "facile"},
    {"question": "Quelle fête a lieu le 25 décembre ?", "answer": "Noël", "explanation": "Fête chrétienne et populaire.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « ouvert » ?", "answer": "Fermé", "explanation": "Antonyme.", "difficulty": "facile"},
    # --- Moyen (lot 4) ---
    {"question": "Quel président américain figure sur le billet de 1 dollar ?", "answer": "George Washington", "explanation": "Premier président des États-Unis.", "difficulty": "moyen"},
    {"question": "Quelle est la plus grande planète du système solaire ?", "answer": "Jupiter", "explanation": "Géante gazeuse.", "difficulty": "moyen"},
    {"question": "Qui a écrit « Roméo et Juliette » ?", "answer": "William Shakespeare", "explanation": "Tragédie de la fin du XVIe siècle.", "difficulty": "moyen"},
    {"question": "Quel est le pays d'origine des Jeux olympiques antiques ?", "answer": "La Grèce", "explanation": "À Olympie, dès 776 av. J.-C.", "difficulty": "moyen"},
    {"question": "Combien de joueurs dans une équipe de rugby à XV sur le terrain ?", "answer": "15", "explanation": "Quinze joueurs par équipe.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de la Belgique ?", "answer": "Bruxelles", "explanation": "Siège de plusieurs institutions européennes.", "difficulty": "moyen"},
    {"question": "Quel organe filtre le sang et produit l'urine ?", "answer": "Les reins", "explanation": "Deux reins filtrent le sang.", "difficulty": "moyen"},
    {"question": "Quel artiste a chanté « Bohemian Rhapsody » avec Queen ?", "answer": "Freddie Mercury", "explanation": "Sortie en 1975.", "difficulty": "moyen"},
    {"question": "Quelle est la monnaie du Royaume-Uni ?", "answer": "La livre sterling", "explanation": "Symbole £.", "difficulty": "moyen"},
    {"question": "Quel fleuve traverse Londres ?", "answer": "La Tamise", "explanation": "Traverse la capitale britannique.", "difficulty": "moyen"},
    {"question": "Combien de continents commencent par la lettre A ?", "answer": "3", "explanation": "Afrique, Asie, Amérique (Nord et Sud), Antarctique — selon le découpage.", "difficulty": "moyen"},
    {"question": "Quel scientifique a énoncé les trois lois du mouvement ?", "answer": "Isaac Newton", "explanation": "Publiées dans les Principia (1687).", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de la Russie ?", "answer": "Moscou", "explanation": "Plus grande ville d'Europe.", "difficulty": "moyen"},
    {"question": "Quel instrument mesure la température ?", "answer": "Le thermomètre", "explanation": "Gradué en degrés.", "difficulty": "moyen"},
    {"question": "En quelle année l'euro est-il entré en circulation (pièces et billets) ?", "answer": "2002", "explanation": "Le 1er janvier 2002.", "difficulty": "moyen"},
    {"question": "Quel pays a la forme d'une botte ?", "answer": "L'Italie", "explanation": "Sa péninsule ressemble à une botte.", "difficulty": "moyen"},
    {"question": "Qui a peint « La Cène » ?", "answer": "Léonard de Vinci", "explanation": "Fresque à Milan, fin XVe siècle.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand État des États-Unis par superficie ?", "answer": "L'Alaska", "explanation": "Bien plus grand que le Texas.", "difficulty": "moyen"},
    # --- Difficile (lot 4) ---
    {"question": "Quel est le numéro atomique de l'hydrogène ?", "answer": "1", "explanation": "Premier élément du tableau périodique.", "difficulty": "difficile"},
    {"question": "Qui a écrit « L'Étranger » ?", "answer": "Albert Camus", "explanation": "Roman de 1942, prix Nobel 1957.", "difficulty": "difficile"},
    {"question": "Quelle dynastie a construit la Cité interdite ?", "answer": "La dynastie Ming", "explanation": "Au début du XVe siècle à Pékin.", "difficulty": "difficile"},
    {"question": "Quel est le point le plus profond des océans ?", "answer": "La fosse des Mariannes", "explanation": "Près de 11 000 m de profondeur.", "difficulty": "difficile"},
    {"question": "Qui a composé « Les Quatre Saisons » ?", "answer": "Antonio Vivaldi", "explanation": "Concertos pour violon (vers 1725).", "difficulty": "difficile"},
    {"question": "Quel est le symbole chimique du potassium ?", "answer": "K", "explanation": "Du latin « kalium ».", "difficulty": "difficile"},
    {"question": "En quelle année a été proclamée la Ve République française ?", "answer": "1958", "explanation": "Nouvelle Constitution sous de Gaulle.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Argentine ?", "answer": "Buenos Aires", "explanation": "Sur le Rio de la Plata.", "difficulty": "difficile"},
    {"question": "Quel physicien a découvert la radioactivité avec les Curie ?", "answer": "Henri Becquerel", "explanation": "Prix Nobel de physique 1903.", "difficulty": "difficile"},
    {"question": "Combien de cœurs possède une pieuvre ?", "answer": "3", "explanation": "Deux branchiaux et un systémique.", "difficulty": "difficile"},
    {"question": "Qui a écrit « Don Quichotte » ?", "answer": "Miguel de Cervantès", "explanation": "Publié en 1605 et 1615.", "difficulty": "difficile"},
    {"question": "Quelle est la plus haute montagne d'Afrique ?", "answer": "Le Kilimandjaro", "explanation": "5 895 m, en Tanzanie.", "difficulty": "difficile"},
    {"question": "Quel traité a mis fin à la Première Guerre mondiale ?", "answer": "Le traité de Versailles", "explanation": "Signé en 1919.", "difficulty": "difficile"},
    {"question": "Quel est l'élément chimique de symbole « Fe » ?", "answer": "Le fer", "explanation": "Du latin « ferrum ».", "difficulty": "difficile"},
    {"question": "Qui a peint « Le Cri » ?", "answer": "Edvard Munch", "explanation": "Œuvre expressionniste de 1893.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Norvège ?", "answer": "Oslo", "explanation": "Au fond d'un fjord.", "difficulty": "difficile"},
    {"question": "Combien de temps met la lumière du Soleil pour atteindre la Terre ?", "answer": "Environ 8 minutes", "explanation": "8 min 20 s en moyenne.", "difficulty": "difficile"},
    {"question": "Qui a formulé la loi de la gravitation universelle ?", "answer": "Isaac Newton", "explanation": "Publiée en 1687.", "difficulty": "difficile"},
    # --- Facile (lot 5) ---
    {"question": "Quel animal saute et a une poche pour son petit ?", "answer": "Le kangourou", "explanation": "Marsupial australien.", "difficulty": "facile"},
    {"question": "De quelle couleur devient une tomate mûre ?", "answer": "Rouge", "explanation": "Verte avant maturité.", "difficulty": "facile"},
    {"question": "Quel est le roi de la jungle ?", "answer": "Le lion", "explanation": "Surnom traditionnel.", "difficulty": "facile"},
    {"question": "Combien de pattes a un insecte ?", "answer": "6", "explanation": "Trois paires de pattes.", "difficulty": "facile"},
    {"question": "Quelle planète est la nôtre ?", "answer": "La Terre", "explanation": "Troisième depuis le Soleil.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « rapide » ?", "answer": "Lent", "explanation": "Antonyme de vitesse.", "difficulty": "facile"},
    {"question": "Quel animal aboie ?", "answer": "Le chien", "explanation": "L'aboiement du chien.", "difficulty": "facile"},
    {"question": "Combien de centimètres dans un mètre ?", "answer": "100", "explanation": "1 m = 100 cm.", "difficulty": "facile"},
    {"question": "Quel astre brille la nuit en grand nombre ?", "answer": "Les étoiles", "explanation": "Visibles dans le ciel nocturne.", "difficulty": "facile"},
    {"question": "Quelle est la capitale du Portugal ?", "answer": "Lisbonne", "explanation": "Au bord du Tage.", "difficulty": "facile"},
    {"question": "Quel fruit rouge pousse sur le fraisier ?", "answer": "La fraise", "explanation": "Fruit du printemps.", "difficulty": "facile"},
    {"question": "Quel objet sert à écrire au tableau noir ?", "answer": "La craie", "explanation": "Bâtonnet de calcaire.", "difficulty": "facile"},
    {"question": "Quel animal est connu pour sa lenteur et sa carapace ?", "answer": "La tortue", "explanation": "Reptile à carapace.", "difficulty": "facile"},
    {"question": "Combien font 8 + 8 ?", "answer": "16", "explanation": "Addition simple.", "difficulty": "facile"},
    {"question": "Quelle est la couleur du charbon ?", "answer": "Noir", "explanation": "Le charbon est noir.", "difficulty": "facile"},
    {"question": "Quel oiseau ne vole pas et vit en Antarctique ?", "answer": "Le manchot", "explanation": "Le manchot nage mais ne vole pas.", "difficulty": "facile"},
    {"question": "Quel repas prend-on le matin ?", "answer": "Le petit-déjeuner", "explanation": "Premier repas de la journée.", "difficulty": "facile"},
    {"question": "Quelle forme a un ballon de football ?", "answer": "Ronde (sphérique)", "explanation": "Une sphère.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « plein » ?", "answer": "Vide", "explanation": "Antonyme.", "difficulty": "facile"},
    {"question": "Quel animal donne la laine ?", "answer": "Le mouton", "explanation": "Sa toison fournit la laine.", "difficulty": "facile"},
    # --- Moyen (lot 5) ---
    {"question": "Quelle est la capitale de la Grèce ?", "answer": "Athènes", "explanation": "Berceau de la démocratie.", "difficulty": "moyen"},
    {"question": "Qui a inventé l'ampoule électrique pratique ?", "answer": "Thomas Edison", "explanation": "Brevet en 1879.", "difficulty": "moyen"},
    {"question": "Combien de couleurs sur le drapeau français ?", "answer": "3", "explanation": "Bleu, blanc, rouge.", "difficulty": "moyen"},
    {"question": "Quel est le plus petit pays d'Amérique du Sud ?", "answer": "Le Suriname", "explanation": "Sur la côte nord-est.", "difficulty": "moyen"},
    {"question": "Quelle planète est la plus chaude du système solaire ?", "answer": "Vénus", "explanation": "Effet de serre extrême.", "difficulty": "moyen"},
    {"question": "Qui a écrit « Les Trois Mousquetaires » ?", "answer": "Alexandre Dumas", "explanation": "Publié en 1844.", "difficulty": "moyen"},
    {"question": "Quel est le métal liquide à température ambiante ?", "answer": "Le mercure", "explanation": "Seul métal liquide à 20 °C.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale du Maroc ?", "answer": "Rabat", "explanation": "Et non Casablanca.", "difficulty": "moyen"},
    {"question": "Combien de minutes dure un match de football (temps réglementaire) ?", "answer": "90", "explanation": "Deux mi-temps de 45 minutes.", "difficulty": "moyen"},
    {"question": "Quel peintre a fondé le cubisme avec Picasso ?", "answer": "Georges Braque", "explanation": "Début du XXe siècle.", "difficulty": "moyen"},
    {"question": "Quelle est la plus longue muraille du monde ?", "answer": "La Grande Muraille de Chine", "explanation": "Plusieurs milliers de kilomètres.", "difficulty": "moyen"},
    {"question": "Quel gaz fait pétiller les boissons gazeuses ?", "answer": "Le dioxyde de carbone (CO2)", "explanation": "Dissous sous pression.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de la Chine ?", "answer": "Pékin", "explanation": "Aussi appelée Beijing.", "difficulty": "moyen"},
    {"question": "Qui a peint « Impression, soleil levant », à l'origine du mot impressionnisme ?", "answer": "Claude Monet", "explanation": "Tableau de 1872.", "difficulty": "moyen"},
    {"question": "Combien de degrés dans un angle droit ?", "answer": "90", "explanation": "Un quart de tour.", "difficulty": "moyen"},
    {"question": "Quel pays a inventé les Jeux olympiques modernes (initiative de Coubertin) ?", "answer": "La France", "explanation": "Pierre de Coubertin, 1894-1896.", "difficulty": "moyen"},
    {"question": "Quelle est la mer la plus salée du monde ?", "answer": "La mer Morte", "explanation": "On y flotte facilement.", "difficulty": "moyen"},
    {"question": "Quel est l'os le plus long du corps humain ?", "answer": "Le fémur", "explanation": "Os de la cuisse.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale du Mexique ?", "answer": "Mexico", "explanation": "Une des plus grandes villes du monde.", "difficulty": "moyen"},
    {"question": "Quel écrivain a créé le personnage de Sherlock Holmes ?", "answer": "Arthur Conan Doyle", "explanation": "À partir de 1887.", "difficulty": "moyen"},
    # --- Difficile (lot 5) ---
    {"question": "Quelle est l'unité de mesure de la force ?", "answer": "Le newton", "explanation": "Symbole N.", "difficulty": "difficile"},
    {"question": "Qui a écrit « Madame Bovary » ?", "answer": "Gustave Flaubert", "explanation": "Roman de 1857.", "difficulty": "difficile"},
    {"question": "Quelle civilisation a construit Machu Picchu ?", "answer": "Les Incas", "explanation": "Au Pérou, XVe siècle.", "difficulty": "difficile"},
    {"question": "Quel est le gaz le plus léger ?", "answer": "L'hydrogène", "explanation": "Élément le plus léger.", "difficulty": "difficile"},
    {"question": "Qui a peint « La Jeune Fille à la perle » ?", "answer": "Johannes Vermeer", "explanation": "Vers 1665, peintre néerlandais.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Inde ?", "answer": "New Delhi", "explanation": "Et non Mumbai.", "difficulty": "difficile"},
    {"question": "Combien de planètes compte le système solaire ?", "answer": "8", "explanation": "Depuis le reclassement de Pluton en 2006.", "difficulty": "difficile"},
    {"question": "Quel mathématicien a donné son nom à un célèbre triangle de nombres ?", "answer": "Blaise Pascal", "explanation": "Le triangle de Pascal.", "difficulty": "difficile"},
    {"question": "Quel empereur français a été vaincu à Waterloo ?", "answer": "Napoléon Bonaparte", "explanation": "En 1815.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Nouvelle-Zélande ?", "answer": "Wellington", "explanation": "Et non Auckland.", "difficulty": "difficile"},
    {"question": "Quel est l'élément chimique de symbole « Hg » ?", "answer": "Le mercure", "explanation": "Du grec « hydrargyros ».", "difficulty": "difficile"},
    {"question": "Qui a composé « Le Lac des cygnes » ?", "answer": "Piotr Ilitch Tchaïkovski", "explanation": "Ballet de 1876.", "difficulty": "difficile"},
    {"question": "En quelle année Christophe Colomb a-t-il atteint l'Amérique ?", "answer": "1492", "explanation": "Premier voyage.", "difficulty": "difficile"},
    {"question": "Quelle est la plus grande île du monde ?", "answer": "Le Groenland", "explanation": "Environ 2,2 millions de km².", "difficulty": "difficile"},
    {"question": "Quel philosophe a écrit « Ainsi parlait Zarathoustra » ?", "answer": "Friedrich Nietzsche", "explanation": "Publié entre 1883 et 1885.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand organe du corps humain ?", "answer": "La peau", "explanation": "Plus grand organe par surface.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale du Danemark ?", "answer": "Copenhague", "explanation": "Plus grande ville scandinave.", "difficulty": "difficile"},
    {"question": "Qui a peint « Les Demoiselles d'Avignon » ?", "answer": "Pablo Picasso", "explanation": "1907, œuvre fondatrice du cubisme.", "difficulty": "difficile"},
    {"question": "Quel savant a établi le tableau périodique des éléments ?", "answer": "Dmitri Mendeleïev", "explanation": "En 1869.", "difficulty": "difficile"},
    {"question": "Combien de temps dure une rotation complète de la Terre sur elle-même ?", "answer": "24 heures", "explanation": "Environ 23 h 56 min (jour sidéral).", "difficulty": "difficile"},
    # --- Difficile (lot 6) ---
    {"question": "Quel est l'élément chimique de symbole « Pb » ?", "answer": "Le plomb", "explanation": "Du latin « plumbum ».", "difficulty": "difficile"},
    {"question": "Qui a écrit « Le Rouge et le Noir » ?", "answer": "Stendhal", "explanation": "Roman publié en 1830.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Finlande ?", "answer": "Helsinki", "explanation": "Sur le golfe de Finlande.", "difficulty": "difficile"},
    {"question": "Quel physicien a énoncé le principe d'incertitude ?", "answer": "Werner Heisenberg", "explanation": "Mécanique quantique, 1927.", "difficulty": "difficile"},
    {"question": "Quelle bataille marque la fin de la Gaule indépendante en 52 av. J.-C. ?", "answer": "Alésia", "explanation": "Vercingétorix se rend à César.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand lac d'eau douce du monde par superficie ?", "answer": "Le lac Supérieur", "explanation": "En Amérique du Nord.", "difficulty": "difficile"},
    {"question": "Qui a composé l'opéra « La Flûte enchantée » ?", "answer": "Mozart", "explanation": "Créé en 1791.", "difficulty": "difficile"},
    {"question": "Quel est le symbole chimique de l'étain ?", "answer": "Sn", "explanation": "Du latin « stannum ».", "difficulty": "difficile"},
    {"question": "En quelle année a été fondée l'ONU ?", "answer": "1945", "explanation": "Charte signée à San Francisco.", "difficulty": "difficile"},
    {"question": "Quel peintre espagnol est célèbre pour ses montres molles ?", "answer": "Salvador Dalí", "explanation": "« La Persistance de la mémoire ».", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Pologne ?", "answer": "Varsovie", "explanation": "Sur la Vistule.", "difficulty": "difficile"},
    {"question": "Quel scientifique a proposé la théorie de l'évolution par sélection naturelle ?", "answer": "Charles Darwin", "explanation": "« L'Origine des espèces », 1859.", "difficulty": "difficile"},
    {"question": "Quelle unité mesure la fréquence ?", "answer": "Le hertz", "explanation": "Symbole Hz, cycles par seconde.", "difficulty": "difficile"},
    {"question": "Qui a peint « La Liberté guidant le peuple » ?", "answer": "Eugène Delacroix", "explanation": "1830, Révolution de Juillet.", "difficulty": "difficile"},
    {"question": "Quel est le métal le plus abondant dans la croûte terrestre ?", "answer": "L'aluminium", "explanation": "Métal le plus abondant.", "difficulty": "difficile"},
    {"question": "Quelle dynastie régnait sur la France avant la Révolution de 1789 ?", "answer": "Les Bourbons", "explanation": "Louis XVI était un Bourbon.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand satellite naturel de Jupiter ?", "answer": "Ganymède", "explanation": "Plus grande lune du système solaire.", "difficulty": "difficile"},
    {"question": "Qui a écrit « Guerre et Paix » ?", "answer": "Léon Tolstoï", "explanation": "Roman russe, 1869.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Autriche ?", "answer": "Vienne", "explanation": "Sur le Danube.", "difficulty": "difficile"},
    {"question": "Quel est le symbole chimique du calcium ?", "answer": "Ca", "explanation": "Présent dans les os.", "difficulty": "difficile"},
    # --- Difficile / Expert (lot 7) ---
    {"question": "Quelle constante physique vaut environ 6,022 × 10²³ ?", "answer": "Le nombre d'Avogadro", "explanation": "Nombre d'entités dans une mole.", "difficulty": "difficile"},
    {"question": "Qui a démontré le dernier théorème de Fermat en 1994 ?", "answer": "Andrew Wiles", "explanation": "Énoncé non résolu pendant 350 ans.", "difficulty": "difficile"},
    {"question": "Quel est l'organite responsable de la production d'énergie dans la cellule ?", "answer": "La mitochondrie", "explanation": "« Centrale énergétique » de la cellule.", "difficulty": "difficile"},
    {"question": "Dans la mythologie grecque, qui a volé le feu aux dieux ?", "answer": "Prométhée", "explanation": "Il l'offrit aux humains et fut châtié.", "difficulty": "difficile"},
    {"question": "Quel traité de 1648 a mis fin à la guerre de Trente Ans ?", "answer": "Les traités de Westphalie", "explanation": "Fondateurs de l'ordre étatique moderne.", "difficulty": "difficile"},
    {"question": "Quelle est la plus petite particule conservant les propriétés d'un élément chimique ?", "answer": "L'atome", "explanation": "Composé de protons, neutrons, électrons.", "difficulty": "difficile"},
    {"question": "Quel mathématicien suisse a introduit la notation « e » et « i » ?", "answer": "Leonhard Euler", "explanation": "XVIIIe siècle, prolifique.", "difficulty": "difficile"},
    {"question": "Quel pharaon a unifié la Haute et la Basse-Égypte selon la tradition ?", "answer": "Narmer (Ménès)", "explanation": "Vers 3100 av. J.-C.", "difficulty": "difficile"},
    {"question": "Quelle est l'unité SI de la pression ?", "answer": "Le pascal", "explanation": "Symbole Pa = N/m².", "difficulty": "difficile"},
    {"question": "Quel astronome a énoncé les lois du mouvement des planètes ?", "answer": "Johannes Kepler", "explanation": "Trois lois, début XVIIe siècle.", "difficulty": "difficile"},
    {"question": "Quel fleuve d'Asie est le plus long ?", "answer": "Le Yangzi (Yang-Tsé)", "explanation": "Environ 6 300 km, en Chine.", "difficulty": "difficile"},
    {"question": "Qui a écrit « La Divine Comédie » ?", "answer": "Dante Alighieri", "explanation": "Poème du XIVe siècle.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale du Kazakhstan ?", "answer": "Astana", "explanation": "Rebaptisée un temps Noursoultan.", "difficulty": "difficile"},
    {"question": "Quel gaz noble est utilisé dans les enseignes lumineuses rouges ?", "answer": "Le néon", "explanation": "Émet une lumière rouge-orangée.", "difficulty": "difficile"},
    {"question": "Quel empire byzantin avait pour capitale Constantinople ?", "answer": "L'Empire byzantin (romain d'Orient)", "explanation": "Jusqu'en 1453.", "difficulty": "difficile"},
    {"question": "Quelle est la racine carrée de 144 ?", "answer": "12", "explanation": "12 × 12 = 144.", "difficulty": "difficile"},
    {"question": "Quel philosophe allemand a écrit « Critique de la raison pure » ?", "answer": "Emmanuel Kant", "explanation": "Publié en 1781.", "difficulty": "difficile"},
    {"question": "Quel est l'élément chimique le plus abondant dans la croûte terrestre ?", "answer": "L'oxygène", "explanation": "Environ 46 % en masse.", "difficulty": "difficile"},
    {"question": "Quelle dynastie chinoise a précédé la dynastie Ming ?", "answer": "La dynastie Yuan", "explanation": "Dynastie mongole de Kubilai Khan.", "difficulty": "difficile"},
    {"question": "Quel scientifique a découvert les rayons X ?", "answer": "Wilhelm Röntgen", "explanation": "En 1895, premier prix Nobel de physique (1901).", "difficulty": "difficile"},
    {"question": "Dans la mythologie nordique, comment s'appelle le marteau de Thor ?", "answer": "Mjöllnir", "explanation": "Arme du dieu du tonnerre.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Islande ?", "answer": "Reykjavik", "explanation": "Capitale la plus septentrionale du monde.", "difficulty": "difficile"},
    {"question": "Quel théorème relie l'énergie et la masse par E = mc² ?", "answer": "L'équivalence masse-énergie (Einstein)", "explanation": "Relativité restreinte, 1905.", "difficulty": "difficile"},
    {"question": "Qui a peint le « Jardin des délices » ?", "answer": "Jérôme Bosch", "explanation": "Triptyque vers 1500.", "difficulty": "difficile"},
    {"question": "Quel est le seul nombre pair qui soit premier ?", "answer": "2", "explanation": "Tous les autres pairs sont divisibles par 2.", "difficulty": "difficile"},
    # --- Difficile / Expert (lot 8) — thèmes variés (arts, ciné, musique, géo, sport, lettres) ---
    {"question": "Quel réalisateur a tourné « 2001, l'Odyssée de l'espace » ?", "answer": "Stanley Kubrick", "explanation": "Sorti en 1968.", "difficulty": "difficile"},
    {"question": "Quel écrivain colombien a écrit « Cent ans de solitude » ?", "answer": "Gabriel García Márquez", "explanation": "Prix Nobel 1982, réalisme magique.", "difficulty": "difficile"},
    {"question": "Quel film a remporté la première Palme d'or à porter ce nom, en 1955 ?", "answer": "Marty", "explanation": "Réalisé par Delbert Mann.", "difficulty": "difficile"},
    {"question": "Quel compositeur a écrit le « Boléro » ?", "answer": "Maurice Ravel", "explanation": "Créé en 1928.", "difficulty": "difficile"},
    {"question": "Quel peintre est l'auteur de « La Persistance de la mémoire » ?", "answer": "Salvador Dalí", "explanation": "1931, montres molles.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Mongolie ?", "answer": "Oulan-Bator", "explanation": "Capitale la plus froide du monde.", "difficulty": "difficile"},
    {"question": "Dans quelle ville se déroule le roman « Ulysse » de James Joyce ?", "answer": "Dublin", "explanation": "Sur une seule journée, le 16 juin 1904.", "difficulty": "difficile"},
    {"question": "Quel pays a remporté la première Coupe du monde de football en 1930 ?", "answer": "L'Uruguay", "explanation": "À domicile, contre l'Argentine.", "difficulty": "difficile"},
    {"question": "Quel architecte a conçu la Sagrada Família ?", "answer": "Antoni Gaudí", "explanation": "À Barcelone, toujours en construction.", "difficulty": "difficile"},
    {"question": "Quel instrument joue principalement Miles Davis ?", "answer": "La trompette", "explanation": "Légende du jazz.", "difficulty": "difficile"},
    {"question": "Quel mot grec signifie « amour de la sagesse » et a donné « philosophie » ?", "answer": "Philosophia", "explanation": "De « philein » (aimer) et « sophia » (sagesse).", "difficulty": "difficile"},
    {"question": "Quelle est la capitale du Pérou ?", "answer": "Lima", "explanation": "Sur la côte pacifique.", "difficulty": "difficile"},
    {"question": "Quel auteur a créé le détective belge Hercule Poirot ?", "answer": "Agatha Christie", "explanation": "Reine du roman policier.", "difficulty": "difficile"},
    {"question": "Quel groupe a sorti l'album « The Dark Side of the Moon » ?", "answer": "Pink Floyd", "explanation": "Sorti en 1973.", "difficulty": "difficile"},
    {"question": "Quel peintre néerlandais a peint « La Ronde de nuit » ?", "answer": "Rembrandt", "explanation": "1642, chef-d'œuvre baroque.", "difficulty": "difficile"},
    {"question": "Quelle ville accueille le siège de l'UNESCO ?", "answer": "Paris", "explanation": "Organisation de l'ONU pour l'éducation et la culture.", "difficulty": "difficile"},
    {"question": "Quel tennisman détient le plus de titres du Grand Chelem chez les hommes (record récent) ?", "answer": "Novak Djokovic", "explanation": "A dépassé Federer et Nadal.", "difficulty": "difficile"},
    {"question": "Quel dramaturge a écrit « En attendant Godot » ?", "answer": "Samuel Beckett", "explanation": "Théâtre de l'absurde, 1953.", "difficulty": "difficile"},
    {"question": "Quelle est la langue officielle du Brésil ?", "answer": "Le portugais", "explanation": "Seul grand pays lusophone d'Amérique.", "difficulty": "difficile"},
    {"question": "Quel réalisateur japonais a réalisé « Les Sept Samouraïs » ?", "answer": "Akira Kurosawa", "explanation": "Sorti en 1954.", "difficulty": "difficile"},
    {"question": "Quel sculpteur a réalisé « Le Penseur » ?", "answer": "Auguste Rodin", "explanation": "Bronze emblématique.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Croatie ?", "answer": "Zagreb", "explanation": "Au nord-ouest du pays.", "difficulty": "difficile"},
    {"question": "Quel chef d'orchestre du rock a chanté « Like a Rolling Stone » ?", "answer": "Bob Dylan", "explanation": "Prix Nobel de littérature 2016.", "difficulty": "difficile"},
    {"question": "Quel poète a écrit « Les Fleurs du mal » ?", "answer": "Charles Baudelaire", "explanation": "Recueil de 1857.", "difficulty": "difficile"},
    {"question": "Dans quel pays se trouve la ville de Tombouctou ?", "answer": "Le Mali", "explanation": "Cité historique au bord du Sahara.", "difficulty": "difficile"},
    {"question": "Quel cinéaste a réalisé « La La Land » ?", "answer": "Damien Chazelle", "explanation": "Sorti en 2016.", "difficulty": "difficile"},
    {"question": "Quel plat espagnol à base de riz et safran est mondialement connu ?", "answer": "La paella", "explanation": "Originaire de Valence.", "difficulty": "difficile"},
    {"question": "Quel personnage de BD belge est un reporter accompagné de Milou ?", "answer": "Tintin", "explanation": "Créé par Hergé.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Roumanie ?", "answer": "Bucarest", "explanation": "Surnommée le « petit Paris » de l'Est.", "difficulty": "difficile"},
    {"question": "Quel compositeur baroque allemand a écrit « Les Variations Goldberg » ?", "answer": "Jean-Sébastien Bach", "explanation": "Composées vers 1741.", "difficulty": "difficile"},
    # --- Difficile / Expert (lot 9) — tech, éco, droit, médecine, religions, jeux, divers ---
    {"question": "Qui est considéré comme le créateur du World Wide Web en 1989 ?", "answer": "Tim Berners-Lee", "explanation": "Au CERN.", "difficulty": "difficile"},
    {"question": "Que signifie le sigle « HTML » ?", "answer": "HyperText Markup Language", "explanation": "Langage de balisage des pages web.", "difficulty": "difficile"},
    {"question": "Quelle entreprise a créé le système d'exploitation Windows ?", "answer": "Microsoft", "explanation": "Fondée par Bill Gates et Paul Allen.", "difficulty": "difficile"},
    {"question": "Quel langage de programmation a été créé par Guido van Rossum ?", "answer": "Python", "explanation": "Première version en 1991.", "difficulty": "difficile"},
    {"question": "Comment s'appelle la monnaie virtuelle créée par Satoshi Nakamoto en 2009 ?", "answer": "Le Bitcoin", "explanation": "Première cryptomonnaie.", "difficulty": "difficile"},
    {"question": "Quel organe émet la politique monétaire de la zone euro ?", "answer": "La Banque centrale européenne (BCE)", "explanation": "Siège à Francfort.", "difficulty": "difficile"},
    {"question": "Quel économiste a écrit « La Richesse des nations » en 1776 ?", "answer": "Adam Smith", "explanation": "Père de l'économie moderne.", "difficulty": "difficile"},
    {"question": "Comment nomme-t-on la hausse générale et durable des prix ?", "answer": "L'inflation", "explanation": "Baisse du pouvoir d'achat de la monnaie.", "difficulty": "difficile"},
    {"question": "Quelle juridiction internationale siège à La Haye et juge les crimes de guerre ?", "answer": "La Cour pénale internationale (CPI)", "explanation": "Créée par le Statut de Rome (2002).", "difficulty": "difficile"},
    {"question": "Combien de juges composent le Conseil constitutionnel français (membres nommés) ?", "answer": "9", "explanation": "Plus les anciens présidents de la République.", "difficulty": "difficile"},
    {"question": "Quelle hormone est sécrétée par le pancréas pour réguler la glycémie ?", "answer": "L'insuline", "explanation": "Son déficit cause le diabète.", "difficulty": "difficile"},
    {"question": "Combien de paires de nerfs crâniens possède l'être humain ?", "answer": "12", "explanation": "Douze paires.", "difficulty": "difficile"},
    {"question": "Quel groupe sanguin est dit « donneur universel » ?", "answer": "O négatif", "explanation": "Compatible avec tous les receveurs.", "difficulty": "difficile"},
    {"question": "Quel texte sacré est central dans l'islam ?", "answer": "Le Coran", "explanation": "Révélé au prophète Mahomet.", "difficulty": "difficile"},
    {"question": "Quelle religion compte le plus grand nombre d'adeptes dans le monde ?", "answer": "Le christianisme", "explanation": "Environ 2,4 milliards de fidèles.", "difficulty": "difficile"},
    {"question": "Comment s'appelle le lieu de prière des musulmans ?", "answer": "La mosquée", "explanation": "Lieu de culte de l'islam.", "difficulty": "difficile"},
    {"question": "Aux échecs, quelle pièce se déplace en « L » ?", "answer": "Le cavalier", "explanation": "Seule pièce qui saute par-dessus les autres.", "difficulty": "difficile"},
    {"question": "Combien de cases compte un échiquier ?", "answer": "64", "explanation": "8 × 8 cases.", "difficulty": "difficile"},
    {"question": "Quel constructeur automobile a pour emblème un cheval cabré ?", "answer": "Ferrari", "explanation": "Le « Cavallino Rampante ».", "difficulty": "difficile"},
    {"question": "De quel pays la marque automobile Volvo est-elle originaire ?", "answer": "La Suède", "explanation": "Fondée à Göteborg.", "difficulty": "difficile"},
    {"question": "Quel cépage rouge est emblématique de la région de Bordeaux ?", "answer": "Le cabernet sauvignon", "explanation": "Souvent assemblé avec le merlot.", "difficulty": "difficile"},
    {"question": "Comment appelle-t-on la science qui étudie les vins ?", "answer": "L'œnologie", "explanation": "Étude du vin et de sa production.", "difficulty": "difficile"},
    {"question": "Quel plombier moustachu est la mascotte de Nintendo ?", "answer": "Mario", "explanation": "Apparu en 1981 dans Donkey Kong.", "difficulty": "difficile"},
    {"question": "Quel jeu vidéo de blocs cubiques est le plus vendu de l'histoire ?", "answer": "Minecraft", "explanation": "Plus de 300 millions d'exemplaires.", "difficulty": "difficile"},
    {"question": "Quelle langue compte le plus grand nombre de caractères écrits ?", "answer": "Le chinois", "explanation": "Des dizaines de milliers de sinogrammes.", "difficulty": "difficile"},
    {"question": "Comment nomme-t-on un mot qui se lit pareil dans les deux sens ?", "answer": "Un palindrome", "explanation": "Exemple : « kayak ».", "difficulty": "difficile"},
    {"question": "Quelle est l'unité monétaire de l'Inde ?", "answer": "La roupie", "explanation": "Roupie indienne (INR).", "difficulty": "difficile"},
    {"question": "Quel organe est greffé lors d'une transplantation cardiaque ?", "answer": "Le cœur", "explanation": "Première greffe par Christiaan Barnard en 1967.", "difficulty": "difficile"},
    {"question": "Quelle société a conçu le moteur de recherche le plus utilisé au monde ?", "answer": "Google", "explanation": "Fondée en 1998.", "difficulty": "difficile"},
    {"question": "Quel est le nom de la discipline qui étudie les blasons et armoiries ?", "answer": "L'héraldique", "explanation": "Étude des armoiries.", "difficulty": "difficile"},
    # --- Facile (lot 6) — animaux, transports, nature, dessins animés ---
    {"question": "Quel animal change de couleur pour se camoufler ?", "answer": "Le caméléon", "explanation": "Il adapte sa couleur à son environnement.", "difficulty": "facile"},
    {"question": "Combien de bosses a un dromadaire ?", "answer": "Une", "explanation": "Le chameau en a deux.", "difficulty": "facile"},
    {"question": "Quel moyen de transport roule sur des rails ?", "answer": "Le train", "explanation": "Circule sur une voie ferrée.", "difficulty": "facile"},
    {"question": "Quelle souris célèbre a été créée par Walt Disney ?", "answer": "Mickey Mouse", "explanation": "Apparue en 1928.", "difficulty": "facile"},
    {"question": "Quel oiseau blanc symbolise la paix ?", "answer": "La colombe", "explanation": "Symbole universel de paix.", "difficulty": "facile"},
    {"question": "En quel animal se transforme la chenille ?", "answer": "Le papillon", "explanation": "Métamorphose via la chrysalide.", "difficulty": "facile"},
    {"question": "Quel grand oiseau africain court très vite mais ne vole pas ?", "answer": "L'autruche", "explanation": "Plus grand oiseau du monde.", "difficulty": "facile"},
    {"question": "Quelle couleur obtient-on en mélangeant du rouge et du blanc ?", "answer": "Le rose", "explanation": "Rouge éclairci par le blanc.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « monter » ?", "answer": "Descendre", "explanation": "Antonyme de déplacement.", "difficulty": "facile"},
    {"question": "Combien de roues a une moto ?", "answer": "2", "explanation": "Deux roues.", "difficulty": "facile"},
    {"question": "Quel animal aquatique respire grâce à des branchies ?", "answer": "Le poisson", "explanation": "Les branchies filtrent l'oxygène de l'eau.", "difficulty": "facile"},
    {"question": "Quel félin domestique ronronne ?", "answer": "Le chat", "explanation": "Le ronronnement du chat.", "difficulty": "facile"},
    # --- Moyen (lot 6) — JO, géo physique, corps, instruments, sports ---
    {"question": "Combien d'anneaux compte le logo des Jeux olympiques ?", "answer": "5", "explanation": "Les cinq continents.", "difficulty": "moyen"},
    {"question": "Combien de dents possède un adulte (dents de sagesse comprises) ?", "answer": "32", "explanation": "28 sans les dents de sagesse.", "difficulty": "moyen"},
    {"question": "Quelle est la plus haute chaîne de montagnes du monde ?", "answer": "L'Himalaya", "explanation": "Abrite l'Everest.", "difficulty": "moyen"},
    {"question": "Dans quel pays se déroule le tournoi de tennis de Wimbledon ?", "answer": "Le Royaume-Uni", "explanation": "À Londres, sur gazon.", "difficulty": "moyen"},
    {"question": "Quelle planète est connue pour sa Grande Tache rouge ?", "answer": "Jupiter", "explanation": "Tempête géante persistante.", "difficulty": "moyen"},
    {"question": "Quel sport de combat se pratique sur un tatami avec des ceintures de couleur ?", "answer": "Le judo", "explanation": "Art martial d'origine japonaise.", "difficulty": "moyen"},
    {"question": "Combien de joueurs compte une équipe de volley-ball sur le terrain ?", "answer": "6", "explanation": "Six joueurs par équipe.", "difficulty": "moyen"},
    {"question": "Quel fleuve traverse l'Égypte du sud au nord ?", "answer": "Le Nil", "explanation": "Se jette en delta dans la Méditerranée.", "difficulty": "moyen"},
    {"question": "Dans quel pays est né le tango ?", "answer": "L'Argentine", "explanation": "À Buenos Aires.", "difficulty": "moyen"},
    {"question": "Quel est le plus petit continent du monde ?", "answer": "L'Océanie", "explanation": "Centré sur l'Australie.", "difficulty": "moyen"},
    {"question": "Quel instrument à vent possède une anche simple et des clés ?", "answer": "La clarinette", "explanation": "Famille des bois.", "difficulty": "moyen"},
    {"question": "Quel pays a remporté le plus de Coupes du monde de football ?", "answer": "Le Brésil", "explanation": "Cinq titres.", "difficulty": "moyen"},
    # --- Difficile (lot 10) — botanique, zoologie, minéraux, danse, opéra, météo, archi ---
    {"question": "Comment nomme-t-on la peur des araignées ?", "answer": "L'arachnophobie", "explanation": "Phobie spécifique courante.", "difficulty": "difficile"},
    {"question": "Quelle pierre précieuse rouge est une variété de corindon ?", "answer": "Le rubis", "explanation": "Le saphir en est la variété bleue.", "difficulty": "difficile"},
    {"question": "Quelle échelle mesure la force du vent ?", "answer": "L'échelle de Beaufort", "explanation": "De 0 (calme) à 12 (ouragan).", "difficulty": "difficile"},
    {"question": "Quel arbre géant de Californie peut vivre des milliers d'années ?", "answer": "Le séquoia", "explanation": "Parmi les plus grands arbres du monde.", "difficulty": "difficile"},
    {"question": "Comment qualifie-t-on un animal qui mange à la fois végétaux et viande ?", "answer": "Omnivore", "explanation": "Comme l'humain ou l'ours.", "difficulty": "difficile"},
    {"question": "Quelle danse à trois temps est née à Vienne ?", "answer": "La valse", "explanation": "Danse de salon tournante.", "difficulty": "difficile"},
    {"question": "Quel architecte a conçu la pyramide de verre du Louvre ?", "answer": "Ieoh Ming Pei", "explanation": "Inaugurée en 1989.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand félin du monde ?", "answer": "Le tigre", "explanation": "Le tigre de Sibérie est le plus massif.", "difficulty": "difficile"},
    {"question": "Quelle échelle historique mesure la magnitude des séismes ?", "answer": "L'échelle de Richter", "explanation": "Aujourd'hui souvent remplacée par la magnitude de moment.", "difficulty": "difficile"},
    {"question": "Quelle est la plus grande espèce de requin ?", "answer": "Le requin-baleine", "explanation": "Inoffensif, il se nourrit de plancton.", "difficulty": "difficile"},
    {"question": "Quel compositeur a écrit l'opéra « Carmen » ?", "answer": "Georges Bizet", "explanation": "Créé en 1875.", "difficulty": "difficile"},
    {"question": "Quelle épice, issue d'un crocus, est la plus chère du monde au poids ?", "answer": "Le safran", "explanation": "Récolté à la main, fil par fil.", "difficulty": "difficile"},
    # --- Facile (lot 7) — vie quotidienne, objets, animaux, météo ---
    {"question": "Quel objet sert à ouvrir une porte fermée à clé ?", "answer": "La clé", "explanation": "On l'insère dans la serrure.", "difficulty": "facile"},
    {"question": "Quel vêtement met-on aux pieds avant les chaussures ?", "answer": "Les chaussettes", "explanation": "Portées sous les chaussures.", "difficulty": "facile"},
    {"question": "Quel repas prend-on le soir ?", "answer": "Le dîner", "explanation": "Dernier repas de la journée.", "difficulty": "facile"},
    {"question": "Quel animal fait « cocorico » le matin ?", "answer": "Le coq", "explanation": "Le chant du coq.", "difficulty": "facile"},
    {"question": "Combien de roues a un tricycle ?", "answer": "3", "explanation": "« Tri » signifie trois.", "difficulty": "facile"},
    {"question": "Quel goût a le citron ?", "answer": "Acide", "explanation": "Saveur acidulée.", "difficulty": "facile"},
    {"question": "Comment appelle-t-on l'eau qui tombe du ciel ?", "answer": "La pluie", "explanation": "Précipitation liquide.", "difficulty": "facile"},
    {"question": "Quel animal lent se déplace avec sa coquille sur le dos ?", "answer": "L'escargot", "explanation": "Gastéropode à coquille.", "difficulty": "facile"},
    {"question": "Quel est le contraire de « propre » ?", "answer": "Sale", "explanation": "Antonyme.", "difficulty": "facile"},
    {"question": "Quel animal aime le fromage et est chassé par le chat ?", "answer": "La souris", "explanation": "Petit rongeur.", "difficulty": "facile"},
    {"question": "Combien de jambes a un être humain ?", "answer": "2", "explanation": "Deux jambes.", "difficulty": "facile"},
    {"question": "Quel astre apporte la lumière du jour ?", "answer": "Le Soleil", "explanation": "Notre étoile.", "difficulty": "facile"},
    # --- Moyen (lot 7) — monuments, mythologie romaine, drapeaux, gastronomie, espace ---
    {"question": "Quelle déesse romaine de l'amour correspond à l'Aphrodite grecque ?", "answer": "Vénus", "explanation": "Déesse de l'amour et de la beauté.", "difficulty": "moyen"},
    {"question": "Quel écrivain britannique a créé Harry Potter ?", "answer": "J.K. Rowling", "explanation": "Saga publiée dès 1997.", "difficulty": "moyen"},
    {"question": "Quel pays est célèbre pour ses tulipes et ses moulins à vent ?", "answer": "Les Pays-Bas", "explanation": "Aussi appelés Hollande.", "difficulty": "moyen"},
    {"question": "Quelle monnaie utilise-t-on aux États-Unis ?", "answer": "Le dollar", "explanation": "Dollar américain (USD).", "difficulty": "moyen"},
    {"question": "Quel fromage italien filant garnit traditionnellement la pizza ?", "answer": "La mozzarella", "explanation": "Fromage à pâte filée.", "difficulty": "moyen"},
    {"question": "Quel océan entoure le pôle Nord ?", "answer": "L'océan Arctique", "explanation": "Le plus petit et le plus froid.", "difficulty": "moyen"},
    {"question": "Quelle ville est surnommée « la Ville Lumière » ?", "answer": "Paris", "explanation": "Pour son éclairage et son rayonnement.", "difficulty": "moyen"},
    {"question": "Quel sport olympique d'hiver combine ski de fond et tir à la carabine ?", "answer": "Le biathlon", "explanation": "Endurance et précision.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand pays d'Afrique par superficie ?", "answer": "L'Algérie", "explanation": "Depuis la partition du Soudan.", "difficulty": "moyen"},
    {"question": "Quelle planète est la plus proche en taille de la Terre ?", "answer": "Vénus", "explanation": "Parfois appelée la « jumelle » de la Terre.", "difficulty": "moyen"},
    {"question": "Quel pays a inventé le sauna ?", "answer": "La Finlande", "explanation": "Tradition nationale.", "difficulty": "moyen"},
    {"question": "Quel monument de Rome était une arène de combats de gladiateurs ?", "answer": "Le Colisée", "explanation": "Amphithéâtre antique.", "difficulty": "moyen"},
    # --- Difficile (lot 11) — vexillologie, géo, langues, gastronomie, musique, anatomie ---
    {"question": "Comment s'appelle l'étude des drapeaux ?", "answer": "La vexillologie", "explanation": "Du latin « vexillum ».", "difficulty": "difficile"},
    {"question": "Quel détroit sépare l'Espagne du Maroc ?", "answer": "Le détroit de Gibraltar", "explanation": "Relie Atlantique et Méditerranée.", "difficulty": "difficile"},
    {"question": "Quel est le plus grand désert du monde (toutes catégories) ?", "answer": "L'Antarctique", "explanation": "Un désert froid, le plus vaste.", "difficulty": "difficile"},
    {"question": "Quelle langue maternelle est la plus parlée dans l'Union européenne ?", "answer": "L'allemand", "explanation": "Devant le français et l'italien.", "difficulty": "difficile"},
    {"question": "Dans quelle ville est remis le prix Nobel de la paix ?", "answer": "Oslo", "explanation": "Les autres Nobel sont remis à Stockholm.", "difficulty": "difficile"},
    {"question": "Quel genre musical est né à La Nouvelle-Orléans au début du XXe siècle ?", "answer": "Le jazz", "explanation": "Métissage afro-américain.", "difficulty": "difficile"},
    {"question": "Quel muscle sépare le thorax de l'abdomen et permet la respiration ?", "answer": "Le diaphragme", "explanation": "Muscle respiratoire principal.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Hongrie ?", "answer": "Budapest", "explanation": "Traversée par le Danube.", "difficulty": "difficile"},
    {"question": "Quel écrivain russe a écrit « Anna Karénine » ?", "answer": "Léon Tolstoï", "explanation": "Publié en 1877.", "difficulty": "difficile"},
    {"question": "Comment nomme-t-on la science de la fabrication des cartes ?", "answer": "La cartographie", "explanation": "Représentation de la Terre sur cartes.", "difficulty": "difficile"},
    {"question": "Quel plat japonais associe riz vinaigré et poisson cru ?", "answer": "Le sushi", "explanation": "Cuisine traditionnelle japonaise.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Turquie ?", "answer": "Ankara", "explanation": "Et non Istanbul.", "difficulty": "difficile"},
    # --- Facile (lot 8) — formes, corps, ferme, météo, fruits ---
    {"question": "Combien de côtés a un triangle ?", "answer": "3", "explanation": "Trois côtés, trois angles.", "difficulty": "facile"},
    {"question": "Combien de côtés a un carré ?", "answer": "4", "explanation": "Quatre côtés égaux.", "difficulty": "facile"},
    {"question": "Quelle couleur donne le mélange du jaune et du rouge ?", "answer": "Orange", "explanation": "Couleur secondaire.", "difficulty": "facile"},
    {"question": "Quelle partie du corps sert à voir ?", "answer": "Les yeux", "explanation": "Organes de la vue.", "difficulty": "facile"},
    {"question": "Quel mois vient juste avant décembre ?", "answer": "Novembre", "explanation": "11e mois de l'année.", "difficulty": "facile"},
    {"question": "Quel animal de la ferme pond des œufs ?", "answer": "La poule", "explanation": "Œufs de poule.", "difficulty": "facile"},
    {"question": "Comment appelle-t-on l'eau gelée blanche qui tombe en hiver ?", "answer": "La neige", "explanation": "Cristaux de glace.", "difficulty": "facile"},
    {"question": "Quel fruit en grappe sert à faire le vin ?", "answer": "Le raisin", "explanation": "Pressé pour le jus puis le vin.", "difficulty": "facile"},
    {"question": "Combien font 2 fois 5 ?", "answer": "10", "explanation": "Table de 5.", "difficulty": "facile"},
    {"question": "Quelle partie du corps sert à entendre ?", "answer": "Les oreilles", "explanation": "Organes de l'ouïe.", "difficulty": "facile"},
    {"question": "Quel oiseau nocturne hulule la nuit ?", "answer": "Le hibou", "explanation": "La chouette aussi.", "difficulty": "facile"},
    {"question": "Quel légume jaune pousse en épi ?", "answer": "Le maïs", "explanation": "Épi à grains jaunes.", "difficulty": "facile"},
    # --- Moyen (lot 8) — inventions, mythologie égyptienne, capitales, records ---
    {"question": "Qui est crédité de l'invention du téléphone ?", "answer": "Alexander Graham Bell", "explanation": "Brevet en 1876.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de la Suède ?", "answer": "Stockholm", "explanation": "Bâtie sur des îles.", "difficulty": "moyen"},
    {"question": "Quel est l'animal terrestre le plus rapide ?", "answer": "Le guépard", "explanation": "Jusqu'à 110 km/h.", "difficulty": "moyen"},
    {"question": "Quelle planète tourne quasiment couchée sur son axe ?", "answer": "Uranus", "explanation": "Axe incliné d'environ 98°.", "difficulty": "moyen"},
    {"question": "Quel auteur a écrit « Le Seigneur des anneaux » ?", "answer": "J.R.R. Tolkien", "explanation": "Publié dans les années 1950.", "difficulty": "moyen"},
    {"question": "Combien de cordes possède un violon ?", "answer": "4", "explanation": "Sol, ré, la, mi.", "difficulty": "moyen"},
    {"question": "Dans quel pays le yoga a-t-il été créé ?", "answer": "L'Inde", "explanation": "Pratique millénaire.", "difficulty": "moyen"},
    {"question": "Quel est le plus grand lac d'Afrique ?", "answer": "Le lac Victoria", "explanation": "Partagé entre trois pays.", "difficulty": "moyen"},
    {"question": "Quel événement la France célèbre-t-elle le 14 juillet ?", "answer": "La fête nationale", "explanation": "Anniversaire de la prise de la Bastille.", "difficulty": "moyen"},
    {"question": "Quel sport se joue avec une crosse et un palet sur la glace ?", "answer": "Le hockey sur glace", "explanation": "Très populaire au Canada.", "difficulty": "moyen"},
    {"question": "Dans quelle ville italienne se trouve la célèbre tour penchée ?", "answer": "Pise", "explanation": "En Toscane.", "difficulty": "moyen"},
    # --- Difficile (lot 12) — chimie, volcans, îles, art, vitamines, astronomie, philo ---
    {"question": "Quel est le symbole chimique du cuivre ?", "answer": "Cu", "explanation": "Du latin « cuprum ».", "difficulty": "difficile"},
    {"question": "Quel volcan a enseveli Pompéi en l'an 79 ?", "answer": "Le Vésuve", "explanation": "Près de Naples.", "difficulty": "difficile"},
    {"question": "Quelle est la plus grande île de la mer Méditerranée ?", "answer": "La Sicile", "explanation": "Devant la Sardaigne.", "difficulty": "difficile"},
    {"question": "À quel mouvement artistique appartient Claude Monet ?", "answer": "L'impressionnisme", "explanation": "Mouvement de la fin du XIXe siècle.", "difficulty": "difficile"},
    {"question": "Quelle vitamine est synthétisée par la peau grâce au soleil ?", "answer": "La vitamine D", "explanation": "Importante pour les os.", "difficulty": "difficile"},
    {"question": "Quelle est la valeur approchée du nombre pi ?", "answer": "3,14", "explanation": "Rapport circonférence/diamètre.", "difficulty": "difficile"},
    {"question": "Quel astronome a défendu l'héliocentrisme au XVIe siècle ?", "answer": "Nicolas Copernic", "explanation": "Le Soleil au centre.", "difficulty": "difficile"},
    {"question": "Quel est l'animal le plus rapide du monde (en piqué) ?", "answer": "Le faucon pèlerin", "explanation": "Plus de 300 km/h en piqué.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de la Suisse ?", "answer": "Berne", "explanation": "Et non Genève ou Zurich.", "difficulty": "difficile"},
    {"question": "Quel philosophe grec fut condamné à boire la ciguë ?", "answer": "Socrate", "explanation": "En 399 av. J.-C. à Athènes.", "difficulty": "difficile"},
    {"question": "Quelle est l'étoile la plus proche de la Terre après le Soleil ?", "answer": "Proxima du Centaure", "explanation": "À environ 4,2 années-lumière.", "difficulty": "difficile"},
    {"question": "Quel pays hispanophone est le plus peuplé du monde ?", "answer": "Le Mexique", "explanation": "Plus de 120 millions d'habitants.", "difficulty": "difficile"},
    # --- Facile (lot 9) — vêtements, métiers, maison, animaux, nombres ---
    {"question": "Quel vêtement protège la tête du froid ?", "answer": "Le bonnet", "explanation": "Couvre-chef d'hiver.", "difficulty": "facile"},
    {"question": "Quel animal hennit ?", "answer": "Le cheval", "explanation": "Le hennissement du cheval.", "difficulty": "facile"},
    {"question": "Combien de doigts a-t-on sur les deux mains ?", "answer": "10", "explanation": "Cinq par main.", "difficulty": "facile"},
    {"question": "Quel moyen de transport navigue sur l'eau ?", "answer": "Le bateau", "explanation": "Transport maritime ou fluvial.", "difficulty": "facile"},
    {"question": "Quel aliment sucré les abeilles fabriquent-elles ?", "answer": "Le miel", "explanation": "À partir du nectar des fleurs.", "difficulty": "facile"},
    {"question": "Quels sont les deux jours du week-end ?", "answer": "Samedi et dimanche", "explanation": "Fin de semaine.", "difficulty": "facile"},
    {"question": "Quel métier soigne les personnes malades ?", "answer": "Le médecin", "explanation": "Professionnel de santé.", "difficulty": "facile"},
    {"question": "De quelle couleur est la neige ?", "answer": "Blanche", "explanation": "Cristaux de glace réfléchissant la lumière.", "difficulty": "facile"},
    {"question": "Quel objet sert à se protéger de la pluie ?", "answer": "Le parapluie", "explanation": "On l'ouvre au-dessus de la tête.", "difficulty": "facile"},
    {"question": "Combien font 6 + 6 ?", "answer": "12", "explanation": "Addition simple.", "difficulty": "facile"},
    {"question": "Quel légume fait pleurer quand on le coupe ?", "answer": "L'oignon", "explanation": "Libère un composé irritant.", "difficulty": "facile"},
    {"question": "Quel animal grimpe aux arbres et adore les bananes ?", "answer": "Le singe", "explanation": "Primate agile.", "difficulty": "facile"},
    # --- Moyen (lot 9) — contes, capitales, sports, nature, espace ---
    {"question": "Quel auteur français a écrit les contes « Cendrillon » et « Le Petit Chaperon rouge » ?", "answer": "Charles Perrault", "explanation": "Contes publiés en 1697.", "difficulty": "moyen"},
    {"question": "Quelle est la capitale de l'Irlande ?", "answer": "Dublin", "explanation": "Sur la côte est.", "difficulty": "moyen"},
    {"question": "Combien de trous compte un parcours de golf complet ?", "answer": "18", "explanation": "Un parcours standard.", "difficulty": "moyen"},
    {"question": "Quel arbre produit les glands ?", "answer": "Le chêne", "explanation": "Arbre majestueux et longévif.", "difficulty": "moyen"},
    {"question": "Combien de temps met la Terre pour faire le tour du Soleil ?", "answer": "Un an", "explanation": "Environ 365,25 jours.", "difficulty": "moyen"},
    {"question": "Quelle danse rythmée est emblématique du carnaval de Rio ?", "answer": "La samba", "explanation": "Danse brésilienne.", "difficulty": "moyen"},
    {"question": "Quel océan borde la côte ouest des États-Unis ?", "answer": "L'océan Pacifique", "explanation": "Bordant la Californie.", "difficulty": "moyen"},
    {"question": "Quel oiseau est l'emblème des États-Unis ?", "answer": "L'aigle à tête blanche", "explanation": "Le pygargue.", "difficulty": "moyen"},
    {"question": "Combien de joueurs compte une équipe de handball sur le terrain ?", "answer": "7", "explanation": "Six joueurs plus un gardien.", "difficulty": "moyen"},
    {"question": "Quel est le plus haut sommet des Alpes ?", "answer": "Le mont Blanc", "explanation": "4 808 m, entre France et Italie.", "difficulty": "moyen"},
    {"question": "Quel sport olympique consiste à soulever des haltères ?", "answer": "L'haltérophilie", "explanation": "Arraché et épaulé-jeté.", "difficulty": "moyen"},
    {"question": "Quel sculpteur a réalisé le « David » de Florence ?", "answer": "Michel-Ange", "explanation": "Statue en marbre (1504).", "difficulty": "moyen"},
    # --- Difficile (lot 13) — histoire de France, géo, biologie, cinéma, musique, maths ---
    {"question": "Quel roi de France est surnommé le « Roi-Soleil » ?", "answer": "Louis XIV", "explanation": "Règne de 1643 à 1715.", "difficulty": "difficile"},
    {"question": "Quelle est la plus grande mer fermée du monde, souvent appelée lac ?", "answer": "La mer Caspienne", "explanation": "Entre Europe et Asie.", "difficulty": "difficile"},
    {"question": "Quel est le symbole chimique du zinc ?", "answer": "Zn", "explanation": "Numéro atomique 30.", "difficulty": "difficile"},
    {"question": "Qui a écrit le roman « 1984 » ?", "answer": "George Orwell", "explanation": "Dystopie publiée en 1949.", "difficulty": "difficile"},
    {"question": "Quelle structure de la cellule contient l'ADN ?", "answer": "Le noyau", "explanation": "Chez les cellules eucaryotes.", "difficulty": "difficile"},
    {"question": "Combien de notes différentes compte une gamme de do majeur ?", "answer": "7", "explanation": "Do, ré, mi, fa, sol, la, si.", "difficulty": "difficile"},
    {"question": "Quel réalisateur a tourné « Citizen Kane » ?", "answer": "Orson Welles", "explanation": "Sorti en 1941.", "difficulty": "difficile"},
    {"question": "Quel fleuve européen se jette dans la mer du Nord près de Rotterdam ?", "answer": "Le Rhin", "explanation": "Traverse plusieurs pays.", "difficulty": "difficile"},
    {"question": "Quelle est la capitale de l'Écosse ?", "answer": "Édimbourg", "explanation": "Et non Glasgow.", "difficulty": "difficile"},
    {"question": "Quel mathématicien grec est l'auteur des « Éléments », base de la géométrie ?", "answer": "Euclide", "explanation": "IIIe siècle av. J.-C.", "difficulty": "difficile"},
    {"question": "Combien de paires de côtes possède l'être humain ?", "answer": "12", "explanation": "Douze paires.", "difficulty": "difficile"},
    {"question": "Quel compositeur a écrit « La Lettre à Élise » ?", "answer": "Ludwig van Beethoven", "explanation": "Bagatelle pour piano.", "difficulty": "difficile"},
]

CULTURE_DIFFICULTIES = {"facile", "moyen", "difficile"}


def pick_culture_questions(difficulty: str, count: int) -> list[dict[str, str]]:
    """Tire `count` questions au hasard, filtrées par difficulté ('toutes' = sans filtre)."""
    normalized = (difficulty or "toutes").strip().lower()
    pool = [q for q in CULTURE_QUESTIONS if normalized == "toutes" or q["difficulty"] == normalized]
    if not pool:
        pool = list(CULTURE_QUESTIONS)
    chosen = random.sample(pool, min(count, len(pool)))
    return [dict(q) for q in chosen]


def pick_one_culture_question(difficulty: str, exclude_questions: set[str]) -> Optional[dict[str, str]]:
    """Tire UNE question au hasard de la difficulté donnée, en évitant celles déjà posées.

    Si toutes les questions de la difficulté ont déjà été posées, on autorise la répétition.
    """
    normalized = (difficulty or "toutes").strip().lower()
    pool = [q for q in CULTURE_QUESTIONS if normalized == "toutes" or q["difficulty"] == normalized]
    if not pool:
        pool = list(CULTURE_QUESTIONS)
    available = [q for q in pool if q["question"] not in exclude_questions] or pool
    if not available:
        return None
    return dict(random.choice(available))
